[package]
name = "bebytes"
version = "1.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/fabracht/bebytes_macro"
description = "A Rust library for serialization and deserialization of network structs."
readme = "README.md"
keywords = ["serialization", "deserialization", "network", "bytes", "no-std"]


[[bin]]
name = "macro_test"
path = "./bin/macro_test.rs"

[dependencies]
bebytes_derive = "1.1.1"

[dev-dependencies]
trybuild = { version = "1.0.102", features = ["diff"] }
test-case = "3.3.1"

[features]
default = ["std"]
std = []
