name: Bump Version bebytes

on:
  workflow_dispatch:
    inputs:
      version_component:
        description: 'Version component to bump (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PA_TOKEN }}
          fetch-depth: 0

      - name: Set version component
        id: extract_version
        run: |
          echo "::set-output name=version_component::${{ github.event.inputs.version_component }}"

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Set Git User
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Bump version
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_API_KEY }}
        run: cargo release -v --execute --no-confirm ${{ steps.extract_version.outputs.version_component }}
        working-directory: bebytes
