name: Test Branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false
        default: 'feature/direct-buffer-codegen'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Lint with clippy
        run: cargo clippy -- -W clippy::pedantic
      - name: Build (std)
        run: cargo build --verbose
      - name: Build (no_std)
        run: cargo build --no-default-features --verbose
      - name: Run tests (std)
        run: cargo test --verbose
      - name: Run tests (no_std)
        run: cargo test --no-default-features --verbose